### ISSUE TITLE
Display result image instead of result path

### ISSUE THREAD

**Issue by rajmalik145** [imgly/imgly-sdk-android-demo#18]
Hi Im new to android development (and github as well) and I am using your sdk to build an app fro myself where I can edit and post pictures directly to my social media accounts. I have tried for days now but cannot figure out how to display result image after export instead of just its path, can you please help me to figure this out

Regards
Raj

**Comment by svendvd** [comment]
Sorry for that issue.
We have released v2.0.13 your problem should be fixed now.
