### ISSUE TITLE
Image name issue

### ISSUE THREAD

**Issue by Burhan-Picon** [imgly/imgly-sdk-android-demo#20]
image name in path which we getting and the image name which saved in sd card is different(last four digits are not matching).

Plz fix this ASAP

**Comment by besho** [comment]
Same problem paths of 
    String resultPath =
                    data.getStringExtra(CameraPreviewActivity.RESULT_IMAGE_PATH);
            String sourcePath =
                    data.getStringExtra(CameraPreviewActivity.SOURCE_IMAGE_PATH);

is different from paths that saved in sdcard

**Comment by besho** [comment]
Any news about this issue ????????  @maltebaumann

**Comment by satendra02** [comment]
Same issue, unable to see edited image in my gallery.
Plz fix this ASAP

**Comment by maltebaumann** [comment]
Hi folks,
sorry for the delay. We're working on a fix and will release an updated version today.
Thanks for your patience.

**Comment by Burhan-Picon** [comment]
The solution for this is you can provide your own path ,then you will get same path in both case.

**Comment by Burhan-Picon** [comment]
There is one more issue when I select image from gallery sometimes it open image but sometimes it get crashed.

**Comment by maltebaumann** [comment]
@Burhan-Picon:
The crash should be fixed with version 2.0.12RC1 of the SDK. If it's not, please create a separate issue. Thanks for your feedback!

**Comment by thamer898** [comment]
hello @Burhan-Picon 

when i used latest version 2.0.12RC2 this error occured :
**Error:Failed to resolve: rapid.decoder:png-decoder:0.3.0**

Regards

**Comment by SimpleSmiki** [comment]
@thamer898 
Have you added that library in your gradle file?
