### ISSUE TITLE
Strange behaviour in focus section and selecting image from Gallery

### ISSUE THREAD

**Issue by GiliappsA** [imgly/imgly-sdk-android-demo#24]
Sometimes focus section damages images in both linear and circular models.
And sometimes, App exit after selecting image from Gallery.

**Comment by maltebaumann** [comment]
Hi,
please create separate issues for each bug. But it looks like the crashing when selecting images from the Gallery is already covered in issue #25. Could you explain what you mean by 'damaging'? Thanks for your help!

**Comment by GiliappsA** [comment]
Hi dear Malte
Sorry for my English.
I'm sorry for that. I am new in GitHub. But about focus I sent this image to you for checking.

Original was captured:
![original](https://cloud.githubusercontent.com/assets/10566709/19738800/9dba3330-9bc5-11e6-85e8-7e5e5ed7bcde.jpg)
In editing with Focus section (this is damaged image, covered by a copy of up and down sides in Linear Focus)
![in editing](https://cloud.githubusercontent.com/assets/10566709/19738832/b5ed4b04-9bc5-11e6-9347-6de21f45d2da.jpg)
And this is saved image and that issue does not seen anymore and everythings is OK!!!
![saved](https://cloud.githubusercontent.com/assets/10566709/19738860/caec0ffe-9bc5-11e6-9bb9-7d906eee69c6.jpg)

Thank you very much and good luck.

**Comment by svendvd** [comment]
This is difficult to reproduce. 
Is this device specific or have you a any tipp for reproduce?

**Comment by GiliappsA** [comment]
Thanks dear Sven. 
Sorry for my English
I test it only on HTC Desire 816
I see normal focus in smaller images, but some big images have that issue. I test again with new sdk:2.0.13 and open another issue, if see it again.
