### ISSUE TITLE
java.io.FileNotFoundException after done with photo editing

### ISSUE THREAD

**Issue by JigneshPatel23** [imgly/imgly-sdk-android-demo#26]
`10-27 07:28:28.726 15379-17219/com.secreds W/System.err: java.io.FileNotFoundException: /storage/emulated/0/DCIM/secreds/result_1477533508724.jpg: open failed: ENOENT (No such file or directory)
10-27 07:28:28.727 15379-17219/com.secreds W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:452)
10-27 07:28:28.727 15379-17219/com.secreds W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
10-27 07:28:28.728 15379-17219/com.secreds W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
10-27 07:28:28.728 15379-17219/com.secreds W/System.err:     at ly.img.android.sdk.operator.ImageSaveOperation.doOperation(ImageSaveOperation.java:112)
10-27 07:28:28.728 15379-17219/com.secreds W/System.err:     at ly.img.android.sdk.operator.ImageSaveOperation.doOperation(ImageSaveOperation.java:45)
10-27 07:28:28.728 15379-17219/com.secreds W/System.err:     at ly.img.android.sdk.operator.AbstractOperation$1.run(AbstractOperation.java:138)
10-27 07:28:28.728 15379-17219/com.secreds W/System.err:     at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:210)
10-27 07:28:28.728 15379-17219/com.secreds W/System.err:     at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:204)
10-27 07:28:28.729 15379-17219/com.secreds W/System.err:     at ly.img.android.sdk.operator.AbstractOperation.runAndDelegate(AbstractOperation.java:131)
10-27 07:28:28.729 15379-17219/com.secreds W/System.err:     at ly.img.android.sdk.operator.Operator.renderResultOnWorker(Operator.java:117)
10-27 07:28:28.729 15379-17219/com.secreds W/System.err:     at ly.img.android.sdk.operator.Operator$BackgroundRunner.run(Operator.java:200)
10-27 07:28:28.729 15379-17219/com.secreds W/System.err:     at ly.img.android.sdk.utils.ThreadUtils$TaskThread.doTask(ThreadUtils.java:253)
10-27 07:28:28.729 15379-17219/com.secreds W/System.err:     at ly.img.android.sdk.utils.ThreadUtils$TaskThread.run(ThreadUtils.java:236)
10-27 07:28:28.729 15379-17219/com.secreds W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
10-27 07:28:28.730 15379-17219/com.secreds W/System.err:     at libcore.io.Posix.open(Native Method)
10-27 07:28:28.730 15379-17219/com.secreds W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
10-27 07:28:28.731 15379-17219/com.secreds W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:438)
10-27 07:28:28.731 15379-17219/com.secreds W/System.err: 	... 12 more`

**Comment by svendvd** [comment]
Do you use v2.0.12RC2 ?

**Comment by JigneshPatel23** [comment]
Stable release.

**Comment by svendvd** [comment]
The versions from v2.0.0 to v2.0.12RC2 (Release Candidate) are pre releases and not stable.
Now, I we have upload the first stable release of v2. (v2.0.13) 
Please try this version, your problem should be fixed.

**Comment by JigneshPatel23** [comment]
Ok let me try
