### ISSUE TITLE
Sticker does not appear when image is saved

### ISSUE THREAD

**Issue by MrMilo** [imgly/imgly-sdk-android-demo#27]
When I add in the sticker in the editor, and export the image, the result image doesn't have the sticker I added earlier to it.

**Comment by MrMilo** [comment]
p/s: tested with every other tools and only stickers is not adding to the final image, other tools is working as expected

**Comment by GiliappsA** [comment]
I see this error, too.

**Comment by svendvd** [comment]
Oh damn i think we have merged this wrong, i will hotfix it... just a moment please.

**Comment by GiliappsA** [comment]
Thanks and Good luck 👍

**Comment by svendvd** [comment]
Hotfixed in v2.0.14

**Comment by GiliappsA** [comment]
Everythings OK. Thanks dear Sven 👍
