### ISSUE TITLE
Stickers 

### ISSUE THREAD

**Issue by besho** [imgly/imgly-sdk-android-demo#30]
Is there any way to hide stickers section ?

**Comment by pnickv** [comment]
Here is from the initial documentation:

4. Customize SDK config for your own Android App.

// Custom toolset modifications can be done by modify the SettingsList.

SettingsList settingsList = new SettingsList();
settingsList.setEventTracker(new CustomEventTracker(Application.ANALYTICS_TRACK_ID))
settingsList.getConfig().setTools(
    new CropEditorTool(R.string.tool_name_crop, R.drawable.icon_tool_crop),
    new OrientationEditorTool(R.string.tool_name_rotate R.drawable.icon_tool_rotate),
    new Divider(),
    new FilterEditorTool(R.string.tool_name_filter, R.drawable.icon_tool_filters),
    new ColorAdjustmentTool(R.string.tool_name_adjust, R.drawable.icon_tool_adjust),
    new Divider(),
    new TextEditorTool(R.string.tool_name_text, R.drawable.icon_tool_text),
    new StickerEditorTool(R.string.tool_name_sticker, R.drawable.icon_tool_sticker),
    new Divider(),
    new FocusEditorTool(R.string.tool_name_focus, R.drawable.icon_tool_focus),
    new Divider(),
    new BrushEditorTool(R.string.tool_name_brush, R.drawable.icon_tool_brush)
);
new CameraPreviewBuilder(MainActivity.this)
                    .setSettingsList(settingsList)
                    .startActivityForResult(MainActivity.this, CAMERA_PREVIEW_RESULT);

So just comment StickerEditorTool to hide it.
