### ISSUE TITLE
Editor Activity

### ISSUE THREAD

**Issue by besho** [imgly/imgly-sdk-android-demo#31]
After Capturing photo, "X" button for cancel not working

**Comment by besho** [comment]
After Capturing photo, "X" button for cancel not working

**Comment by svendvd** [comment]
Can you please provide more infos?

**Comment by besho** [comment]
After i capture a photo, a footer appeared with "true" sign to save or "x" sign to cancel. "X" is not working when click on it.

**Comment by svendvd** [comment]
This working in the demo of 2.0.24. 
Witch version do you use?
