### ISSUE TITLE
Sticker loading fails for the first time

### ISSUE THREAD

**Issue by SimpleSmiki** [imgly/imgly-sdk-android-demo#32]
When I pick a sticker from the list, I get empty slot instantiated. When I delete it and try again it works. 

Is this due to resource size, maybe?

Any recommendations for the type and size of the resources?

**Comment by svendvd** [comment]
Fixed in v2.0.15, this version is currently not in jCenter.
Please add the imgly maven repo und update it.

repositories {
     jcenter()
     maven {
         url 'https://dl.bintray.com/9elements/ly.img.android/'
     }
 }

**Comment by svendvd** [comment]
Please note, new updates of the Photo-Editor-SDK are not longer in the jCenter or dl.bintray.com repository.
Please look at the documentation how you can add the new `artifactory.9elements.com` repository.
