### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by besho** [imgly/imgly-sdk-android-demo#34]
Sometimes camera open although the screen is black but if you press to capture photo, it captured it successfully. this case happened first time you launch app after long period. This issue is very important in sdk performance

**Comment by NooruddinLakhani** [comment]
Yes this occurred many times but I couldn't get it to solve yet. Have you solved it ?

**Comment by svendvd** [comment]
This is an problem with Android's Camera API v1, we are currently working on this.
