### ISSUE TITLE
Adding sticker resources from external source?

### ISSUE THREAD

**Issue by SimpleSmiki** [imgly/imgly-sdk-android-demo#38]
Is there a possibility for using a stickers that are not in our drawables folders? This can be resource from URL or even something on the device already.

Is it maybe planned for implementing, or how hard would it be to tweak current version for this?

Thanks in advance and keep up the good work!

**Comment by svendvd** [comment]
You can add Stricker from files by using the Uri constructor.

new ImageStickerConfig("Hallo World", Uri.fromFile(previewFile), Uri.fromFile(file));

**Comment by SimpleSmiki** [comment]
Awesome!

**Comment by SimpleSmiki** [comment]
I tried it, and I have the sticker from Uri in editor, but this type of sticker is not appearing in result image.

Am I missing something?

**Comment by svendvd** [comment]
Hi, witch version?

Best,
Sven

**Comment by SimpleSmiki** [comment]
It happens with 2.0.23.

**Comment by svendvd** [comment]
Ok sorry for this and thx for reporting. I have create a bug ticket.
To be sure, it will shown in preview but not in the result?

It's would be helpful if there is any error log out or warning?

**Comment by SimpleSmiki** [comment]
That's correct. I don't have any useful log, though. 

I am using both stickers from Uri and from drawable folder. Those from drawable are applied to result image. 

Additional info - Android 6.0, LG Spirit is the phone model
