### ISSUE TITLE
Stickers and Text Problem 

### ISSUE THREAD

**Issue by karim2016** [imgly/imgly-sdk-android-demo#39]
It's Very Weird but , It is very important to fix that error . 
![screenshot_2016-11-15-17-28-49](https://cloud.githubusercontent.com/assets/9481653/20311863/05c0db34-ab5a-11e6-90db-74e8ee43babb.png)

![screenshot_2016-11-15-17-28-29](https://cloud.githubusercontent.com/assets/9481653/20311862/05b82d04-ab5a-11e6-9f82-90783df63f9a.png)

**Problem is** : When I choose some sticker or when I write some text in the editor screen , sometimes it loads as the attachment ( small item without the main preview ) . 

This problem doesn't happen all time , but it is very important to fix it . 

Hope , to find solution **ASAP .** 

Regards ,

**Comment by karim2016** [comment]
My Problem is fixed according to this answer [](https://github.com/imgly/imgly-sdk-android-demo/issues/32) , 
Thanks to "svendvd" . 
I'm very thankful to him :+1:  :) .

**Comment by simsas18** [comment]
Hello,
I'm having the same problem. Would you mind sharing the fix?
Thanks

**Comment by karim2016** [comment]
Hello , 
Just upgrade the library from gradle file to 2.0.15 
and ,  Please add the imgly maven repo like this 
 maven {
         url 'https://dl.bintray.com/9elements/ly.img.android/'
     }

**Comment by svendvd** [comment]
Please note, new updates of the Photo-Editor-SDK are not longer in the jCenter or dl.bintray.com repository.
Please look at the documentation how you can add the new `artifactory.9elements.com` repository.
