### ISSUE TITLE
I am getting this error in onActivity result method after editing the image

### ISSUE THREAD

**Issue by Rameshsam** [imgly/imgly-sdk-android-demo#40]
java.io.FileNotFoundException: /storage/emulated/0/Download/ImgLy/result_1479500942698.jpg: open failed: ENOENT (No such file or directory)
11-19 01:59:02.698 20405-21209/com.thebaakup W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:452)
11-19 01:59:02.698 20405-21209/com.thebaakup W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
11-19 01:59:02.698 20405-21209/com.thebaakup W/System.err:     at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
11-19 01:59:02.698 20405-21209/com.thebaakup W/System.err:     at ly.img.android.sdk.operator.ImageSaveOperation.doOperation(ImageSaveOperation.java:112)
11-19 01:59:02.698 20405-21209/com.thebaakup W/System.err:     at ly.img.android.sdk.operator.ImageSaveOperation.doOperation(ImageSaveOperation.java:45)
11-19 01:59:02.698 20405-21209/com.thebaakup W/System.err:     at ly.img.android.sdk.operator.AbstractOperation$1.run(AbstractOperation.java:138)
11-19 01:59:02.698 20405-21209/com.thebaakup W/System.err:     at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:210)
11-19 01:59:02.698 20405-21209/com.thebaakup W/System.err:     at ly.img.android.sdk.operator.ChunkIntermediary.combineChunkRequests(ChunkIntermediary.java:204)
11-19 01:59:02.698 20405-21209/com.thebaakup W/System.err:     at ly.img.android.sdk.operator.AbstractOperation.runAndDelegate(AbstractOperation.java:131)
11-19 01:59:02.698 20405-21209/com.thebaakup W/System.err:     at ly.img.android.sdk.operator.Operator.renderResultOnWorker(Operator.java:117)
11-19 01:59:02.699 20405-21209/com.thebaakup W/System.err:     at ly.img.android.sdk.operator.Operator$BackgroundRunner.run(Operator.java:200)
11-19 01:59:02.699 20405-21209/com.thebaakup W/System.err:     at ly.img.android.sdk.utils.ThreadUtils$TaskThread.doTask(ThreadUtils.java:253)
11-19 01:59:02.699 20405-21209/com.thebaakup W/System.err:     at ly.img.android.sdk.utils.ThreadUtils$TaskThread.run(ThreadUtils.java:236)
11-19 01:59:02.699 20405-21209/com.thebaakup W/System.err: Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
11-19 01:59:02.699 20405-21209/com.thebaakup W/System.err:     at libcore.io.Posix.open(Native Method)
11-19 01:59:02.699 20405-21209/com.thebaakup W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
11-19 01:59:02.699 20405-21209/com.thebaakup W/System.err:     at libcore.io.IoBridge.open(IoBridge.java:438)

**Comment by svendvd** [comment]
This seems an problem of an older version, which has not create the folder and can't save if the folder not exist .

Please Upgrade to the newest version 2.0.23. 
Please note, new updates of the Photo-Editor-SDK are not longer in the jCenter repository.
Please look at the documentation how you can add the new repository.
