### ISSUE TITLE
Customizing Camera

### ISSUE THREAD

**Issue by NooruddinLakhani** [imgly/imgly-sdk-android-demo#44]
I am not using it's default CameraPreviewActivity class, I am using my own class for Image picker and then applying all it's filters , cropping , stickers etc but I just only want to set it's output file path which is currently sets in SettingList object but I am not calling it's CameraPreviewActivity so how would I achieve this ?

**Comment by svendvd** [comment]
Pass the SettingsList to the PhotoEditorBuilder to open the editor without camera.
