### ISSUE TITLE
Image PPI reduce after saving image from editor sdk

### ISSUE THREAD

**Issue by IbraTq** [imgly/imgly-sdk-android-demo#47]
Hi Imgly team
My photo ppi is 96 pixels-per-inch, but after add some stickers and save , the ppi of image reduce to 72 ppi. Please check

i added setJpegQuality(100) in setting for EditorSaveSettings model

Thanks

**Comment by svendvd** [comment]
Hi PPI is an Exif information.
You need to set the ExifMode.

Change config like this:
```
stateHandler.getSettingsModel(EditorSaveSettings.class)
.setExifMode(new ExifModeCopyAll()) 
```
to copy all exif infos 

or like this:
```
HashSet<Exify.TAG> tags = new HashSet<>();
tags.add(Exify.TAG.X_RESOLUTION);
tags.add(Exify.TAG.Y_RESOLUTION);

stateHandler.getSettingsModel(EditorSaveSettings.class)
.setExifMode(new ExifModeWhiteListCopy(tags))
```
to copy only the PPI Informations.

**Comment by IbraTq** [comment]
Thanks, i will try
