### ISSUE TITLE
 Error inflating class ly.img.android.sdk.views.EditorPreview

### ISSUE THREAD

**Issue by Yogi-p** [imgly/imgly-sdk-android-demo#48]
Error inflating class ly.img.android.sdk.views.EditorPreview while passing an image to 
new PhotoEditorBuilder(getActivity())
                .setSettingsList(settingsList)
                .startActivityForResult(getActivity(),0);

**Comment by svendvd** [comment]
Hi witch version v2.1.1? 
Can you please copy and paste the Stacktrace?
