### ISSUE TITLE
Implementation into Fragment? Customize the Camera layout?

### ISSUE THREAD

**Issue by jantursky** [imgly/imgly-sdk-android-demo#51]
Are there any possibilities to customize **Camera and Editor** layout? I don't like the current look of both screens, so is there any way how to do that? I also wanted to ask - is it possible to implement Camera+Editor funcionality of img.ly into **Fragment**, not Activity? 

Many thanks

**Comment by svendvd** [comment]
Yes you can simply override all layout files, please look at the example code.

**Comment by svendvd** [comment]
Currently no fragment support...
