### ISSUE TITLE
Why image black on the bottom when I save from PhotoEditorSDK. Look photo in the link.

### ISSUE THREAD

**Issue by Khunchheang** [imgly/imgly-sdk-android-demo#54]
https://firebasestorage.googleapis.com/v0/b/vclip-46ea9.appspot.com/o/photo_2017-02-01_16-10-02.jpg?alt=media&token=f1ee22c8-538e-4b1b-9b1e-5aadecfada05

**Comment by Ulseyha** [comment]
what is the that you saved?

**Comment by svendvd** [comment]
Is this v2.1.3?

**Comment by Khunchheang** [comment]
It's v2.0.13

**Comment by svendvd** [comment]
Oh okay this is an know bug in v2.0.13 please use v2.1.3. The API should be almost the same.
