### ISSUE TITLE
Sticker added from URI did not appear in final result.

### ISSUE THREAD

**Issue by MrMilo** [imgly/imgly-sdk-android-demo#55]
Hi guys, I tried adding a sticker from URI, it appear correctly in the Editor, but when Export the end result image doesn't have the sticker with it, any idea?

**Comment by MrMilo** [comment]
P/S: I'm using SDK version 2.0.27, I also saw another issue that have same problem but it's closed #38

**Comment by MrMilo** [comment]
Hi! Any update regarding this issues? I tried with the latest version available in the repo (2.1.3) is also having the exact same problem.

**Comment by svendvd** [comment]
We can't fix this in v2 but we have fixed it v3.0.2.

Use ImageSource.create(YOU_URI) as sticker resource, you can also use VectorDrawables.

**Comment by MrMilo** [comment]
Hi @svendvd  thanks for updating, I see v3+ now required a license in-order to use it in our apps. I had contacted the sales yesterday but still haven't get a reply.

Basically we been using the SDK's sticker feature in our apps, but we're not making money from it, do we still need to get a commercial license?

**Comment by svendvd** [comment]
Yes, our Sales Team has received your request, an answer takes currently up to 24h.
Thx.
