### ISSUE TITLE
Customizing the BrushEditorTool

### ISSUE THREAD

**Issue by hashchirag** [imgly/imgly-sdk-android-demo#56]
` BrushEditorTool brushEditorTool = new BrushEditorTool(R.string.tool_name_doodle,R.drawable.ic_imgly_brush);
        brushEditorTool.setBrushColor(R.color.colorBlack);`

This is how I'm setting up the brush editor tool. ( I want a different color as the default brush color ) 
But , when I do the following, I get a NPE saying - 

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'ly.img.android.sdk.models.state.BrushLayerSettings ly.img.android.sdk.models.state.BrushLayerSettings.setBrushColor(int)' on a null object reference`

Is there something I'm missing?

**Comment by svendvd** [comment]
Please use the SettingsList to configure this
```
settingsList.getSettingsModel(BrushLayerSettings.class).setBrushColor(getResources().getColor(R.color.your_color));
```

Do not forget to add your custom colors to the brush colors config
```
settingsList.getConfig().setBrushColors(
                new ColorConfig("Color accessibility name", getResources().getColor(R.color.your_color))
                ...
)
```
