### ISSUE TITLE
App size

### ISSUE THREAD

**Issue by chiragshenoy** [imgly/imgly-sdk-android-demo#57]
I would like to use only CropEditorTool , TextEditorTool and BrushEditorTool and Divider in the app.
The sdk size seems to be too big considering that our app size itself is 7MB.
Is there a way we can reduce the library size even more using Proguard? ( 3 to 4 MB is also quite large)

**Comment by svendvd** [comment]
I suppose you have already removed all stickers and LUTs, so there is no more optimization potential. We used the RenderScripts support lib (2-3MB) for chunked rendering to support large images on low-end devices
