### ISSUE TITLE
Crop aspect name cannot be passed as string besides @StringRes

### ISSUE THREAD

**Issue by mikeseng** [imgly/imgly-sdk-android-demo#58]
I'm utilizing the sdk as which the crop aspects is very dynamic. So, I want to config the aspect size whenever user choose which size. It seem to have no problem with the size itself, however, the name of the crop size has to be predefined in String Resource. 

Would there be a way to customize this?

**Comment by svendvd** [comment]
You can override the getName() Method. 

```
package ly.img.android.sdk.models.config;

public class CropAspectWithStringNameConfig extends CropAspectConfig {
    
    private String name;
    
    public CropAspectWithStringNameConfig(String name, int cropWidth, int cropHeight) {
        super(R.string.some_dummy_string_res, cropWidth, cropHeight);
        this.name = name;
    }

    @Override
    public String getName() {
        return name;
    }
    
}```

**Comment by mikeseng** [comment]
That does not change anything.
