### ISSUE TITLE
No compress image

### ISSUE THREAD

**Issue by charleston10** [imgly/imgly-sdk-android-demo#9]
I tried several times the compression of image
I put a image of 4K and others

Example test:
21800px 10400px - Large scale
12000px 6000px - Scale medium
4000px 2000px - Scale standard

The application end with error

**Comment by svendvd** [comment]
I don't understand what you doing. 
What error from our SDK do you have?

**Comment by charleston10** [comment]
**"application stopped unexpectedly"**

You can do try the test

Put this picture
[Link download: https://commons.wikimedia.org/wiki/Atlas_of_the_world#/media/File:Whole_world_-_land_and_oceans_12000.jpg](url)

**Comment by svendvd** [comment]
At the moment the SDK have an hardware limitation on the memory. 
A single android app has a limited memory heap. (128MB - 512MB depending on device)
24000 x 12000 = 288.000.000 x 4 Color = 1,1GB Memory usage is too much.

We trying to fix this in a future version, with a chunk rendering pipeline.

**Comment by charleston10** [comment]
Thank you very much.

Maybe this can help you.
I solved this problem using this library for compact picture
[https://github.com/zetbaitsu/Compressor](url)

**Comment by svendvd** [comment]
No, this is not the problem. It is not simply a compression problem.

When you doing Image Processing the Image is uncompressed as an Bitmap in the Memory. The Image File size is not necessary, only the pixel count.

If we want to support images bigger than the hardware limitations, we must multiple times load only a chunk of the full image from the disk, than render it and put, this chunk back to the disk.

**Comment by charleston10** [comment]
The problem I identified was to save the image, because it took a while to render on screen.
So I figured that was not compressing the file, because the android 19 or higher devices can save up 4Mp
With this library "compress" I saved image with 2Mp ou 4Mp, bacause picuture is 24Mp and not given error

**Comment by vicktorManuel** [comment]
how do you compress the image charleston?, I try compress, buy i can't this

**Comment by svendvd** [comment]
We developed a completely new rendering pipeline. And have that integrated in the next version 2.0.X (currently in closed beta).
Now we can edit and save images with up to 65536 x 65536 Pixel = 4294MegaPixel (this is the maximum JPEG limit) without produce "out of memory" errors even on low memory devices.
